### ISSUE TITLE
Can't compile using nimble

### ISSUE THREAD

**Issue by sdwfrost** [jackmott/nim_simd#3]
Using choosenim nim#devel on OSX, I get the following error when installing with nimble:

```sh
$ nimble install
   Warning: Package 'nimsimd' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nimsimdpkg', but file 'avx.nim' is in a directory named 'nimsimd' instead. This will be an error in the future.
      Hint: If 'nimsimd' contains source files for building 'nimsimd', rename it to 'nimsimdpkg'. Otherwise, prevent its installation by adding `skipDirs = @["nimsimd"]` to the .nimble file.
  Verifying dependencies for nimsimd@0.1.0
   Warning: No nimblemeta.json file found in /Users/simon/.nimble/pkgs/nimsimd-0.1.0
 Installing nimsimd@0.1.0
   Building nimsimd/nimsimd using c backend
Error: unhandled exception: Is a directory [OSError]
```

**Comment by ghost** [comment]
@jackmott 
This line should be removed from nimble to fix this issue, because as I think nimsimd doesn't need to provide any binaries to actual users of it:
https://github.com/jackmott/nim_simd/blob/master/nimsimd.nimble#L7

**Comment by sdwfrost** [comment]
This fixes the compilation problem. Would it be possible to have an examples or test directory with some minimal code to test whether the package works properly?

**Comment by jackmott** [comment]
I've made an examples directory, you should be able to compile and run simple.nim and verify that the two arrays are added, and that it is detecting your cpu correctly.   There is also a simplex_noise.nim which is not fully working yet.
